<div dir="rtl" style="text-align: right;">
<li>معرفی</li>
<p>NumPy یک کتابخانه برای زبان برنامه‌نویسی پایتون است که از آرایه‌ها و ماتریس‌های بزرگ و چندبعدی پشتیبانی می‌کند، همراه با مجموعه‌ای بزرگ از توابع ریاضی سطح بالا برای عملیات روی این آرایه‌ها.</p>
</div>


<div dir="rtl" style="text-align: right;">
<h1>ایجاد در NumPy</h1>

<p>برای استفاده از numpy، کتابخانه numpy را وارد کنید.</p>
<pre>import numpy</pre>


</div>


In [35]:
import numpy

<div dir="rtl" style="text-align: right;">




<h2>ایجاد یک آرایه از صفرها</h2>
<p>برای ایجاد یک آرایه numpy حاوی صفرها، بنویسید: <code>np.zeros(size)</code></p>
<p>برای ایجاد یک آرایه به اندازه ۹ بنویسید: <code>np.zeros(9)</code></p>




</div>

In [36]:
import numpy as np
Z=np.zeros(9)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


<div dir="rtl" style="text-align: right;">




<h2>ایجاد یک آرایه از یک‌ها</h2>
<p>برای ایجاد یک آرایه numpy حاوی یک‌ها، بنویسید: <code>np.ones(size)</code>.</p>
<p>برای ایجاد یک آرایه به اندازه ۹ بنویسید: <code>np.ones(9)</code></p>



</div>

In [37]:
import numpy as np
Z = np.ones(9)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


<div dir="rtl" style="text-align: right;">



<h2>ایجاد یک آرایه از صفرها و یک‌ها</h2>
<p>برای ایجاد یک آرایه از صفرها و یک‌ها، استفاده کنید از <code>np.array([1,0,0,0,0,0,1,0])</code>:</p>


</div>

In [38]:
import numpy as np
Z = np.array([1,0,0,0,0,0,0,1,0])
print(Z)

[1 0 0 0 0 0 0 1 0]


<div dir="rtl" style="text-align: right;">





<h2>ایجاد یک آرایه از دوها</h2>
<p>برای ایجاد یک آرایه از دوها بنویسید: <code>2*np.ones(size)</code>.</p>
<p>برای ایجاد یک آرایه از دوها به اندازه ۹ بنویسید: <code>2*np.ones(9)</code>.</p>



</div>

In [39]:
import numpy as np
Z = 2*np.ones(9)
print(Z)

[2. 2. 2. 2. 2. 2. 2. 2. 2.]


<div dir="rtl" style="text-align: right;">





<h2>ایجاد یک آرایه NumPy به هر طولی</h2>
<p>برای ایجاد یک آرایه به هر طولی بنویسید: <code>np.arange(size)</code>.</p>
<p>برای ایجاد یک آرایه به اندازه ۹ بنویسید: <code>np.arange(9)</code>.</p>


</div>

In [40]:
import numpy as np
Z = np.arange(9)
print(Z)

[0 1 2 3 4 5 6 7 8]


<div dir="rtl" style="text-align: right;">




<h2>تغییر شکل یک آرایه NumPy به یک بردار ستونی</h2>
<p>برای تغییر شکل یک آرایه numpy، بنویسید: <code>np.arange(size).reshape(size,1)</code>.</p>
<p>برای تغییر شکل یک آرایه numpy به ۹ سطر و ۱ ستون، بنویسید: <code>np.arange(9).reshape(9,1)</code>.</p>


</div>

In [41]:
import numpy as np  
Z = np.arange(9).reshape(9,1)
print(Z)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


<div dir="rtl" style="text-align: right;">


<h2>تولید یک آرایه از اعداد تصادفی و به فرمت شبکه</h2>
<p>برای تولید یک آرایه با اندازه تصادفی، بنویسید: <code>np.random.randint(0,size,(x_dimension,y_dimension))</code>.</p>
<p>برای تولید یک آرایه از اعداد تصادفی از ۰ تا ۹ و با بعد x ۳ و بعد y ۳، بنویسید: <code>np.random.randint(0,9,(3,3))</code>.</p>


</div>

In [42]:
import numpy as np
Z=np.random.randint(0,9,(3,3))
print(Z)

[[7 1 5]
 [7 1 0]
 [0 6 4]]


<div dir="rtl" style="text-align: right;">




<h2>ایجاد یک Linspace</h2>
<p>برای ایجاد اعداد به طور یکنواخت فاصله‌گذاری شده بر روی یک دامنه مشخص بنویسید: <code>np.linspace(start, stop, size)</code></p>
<p>برای ایجاد یک linspace از دامنه ۰-۱ و اندازه ۵، بنویسید: <code>Z = np.linspace(0, 1, 5)</code>.</p>

</div>

In [43]:
import numpy as np 
Z = np.linspace(0, 1, 5)
print(Z)

[0.   0.25 0.5  0.75 1.  ]


<div dir="rtl" style="text-align: right;">



<h2>ایجاد یک شبکه Mesh</h2>
<p>برای ایجاد یک "شبکه مش" چند بعدی، بنویسید: <code>np.mgrid[0:x_dimension,0:y_dimension]</code></p>
<p>برای ایجاد یک شبکه در numpy به اندازه (۳*۳)، بنویسید: <code>np.mgrid[0:3,0:3]</code></p>
</div>

In [44]:
import numpy as np
Z=np.mgrid[0:3,0:3]
print(Z)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


<div dir="rtl" style="text-align: right;">
<h1>تغییر شکل در NumPy</h1>




<p>سینتکس پایه برای تغییر شکل آرایه:</p>
<pre>Z=np.array(1D_array).reshape(x_dimension,y_dimension)</pre>

<h2>مثال‌ها</h2>
<p>مثال‌های زیر نشان می‌دهند چگونه یک آرایه را در ابعاد مختلف تغییر شکل دهیم:</p>

<h3>تغییر شکل به ۱۲ سطر و ۱ ستون</h3>
<p>برای تغییر شکل آرایه به ۱۲ سطر و ۱ ستون بنویسید:</p>
<pre>Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(12,1)</pre>




</div>


In [45]:
import numpy as np
Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(12,1)
print(Z)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]


<div dir="rtl" style="text-align: right;">


<h3>تغییر شکل به ۳ سطر و ۴ ستون</h3>
<p>برای تغییر شکل آرایه به ۳ سطر و ۴ ستون بنویسید:</p>
<pre>Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(3,4)</pre>


</div>

In [46]:
import numpy as np
Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(3,4)
print(Z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]


<div dir="rtl" style="text-align: right;">


<h3>تغییر شکل به ۴ سطر و ۳ ستون</h3>
<p>برای تغییر شکل آرایه به ۴ سطر و ۳ ستون بنویسید:</p>
<pre>Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(4,3)</pre>


</div>

In [47]:
import numpy as np
Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(4,3)
print(Z)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 1 0]]


<div dir="rtl" style="text-align: right;">



<h3>تغییر شکل به ۶ سطر و ۲ ستون</h3>
<p>برای تغییر شکل آرایه به ۶ سطر و ۲ ستون بنویسید:</p>
<pre>Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(6,2)</pre>

<h3>تغییر شکل به ۲ سطر و ۶ ستون</h3>
<p>برای تغییر شکل آرایه به ۲ سطر و ۶ ستون بنویسید:</p>
<pre>Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(2,6)</pre>
</div>

In [48]:
import numpy as np
Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(6,2)
print(Z)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]]


<div dir="rtl" style="text-align: right;">


<h3>تغییر شکل به ۲ سطر و ۶ ستون</h3>
<p>برای تغییر شکل آرایه به ۲ سطر و ۶ ستون بنویسید:</p>
<pre>Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(2,6)</pre>
</div>

In [49]:
import numpy as np
Z = np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(2,6)
print(Z)

[[0 0 0 0 0 0]
 [0 0 0 0 1 0]]


<div dir="rtl" style="text-align: right;">
<h1>اندیس‌گذاری در NumPy</h1>


<p>اندیس‌گذاری به معنای ارجاع به هر مقدار در یک آرایه است. هر آیتم در یک آرایه numpy در یک اندیس خاص ذخیره می‌شود. برای دسترسی به مقدار در یک اندیس خاص بنویسید:</p>

</div>


In [50]:
Z = np.arange(9)
Z[0]  # دریافت مقدار در اندیس 0


0

<div dir="rtl" style="text-align: right;">


<h2>دریافت اولین مقدار</h2>
<p>برای دریافت اولین مقدار یک ماتریس، بنویسید: <code>Z[0,0]</code>.</p>




</div>

In [51]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z[0,0])

0


<div dir="rtl" style="text-align: right;">




<h2>دریافت آخرین مقدار</h2>
<p>برای دریافت آخرین مقدار یک ماتریس، بنویسید: <code>Z[-1,-1]</code>.</p>


</div>

In [52]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z[-1,-1])

8


<div dir="rtl" style="text-align: right;">






<h2>دریافت یک ردیف از یک شبکه</h2>
<p>برای دریافت یک ردیف از یک شبکه، بنویسید: <code>Z[اندیس ردیف]</code>.</p>
<p>برای دریافت اولین ردیف از یک شبکه، بنویسید: <code>Z[0]</code>.</p>


</div>

In [53]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z[1])

[3 4 5]


<div dir="rtl" style="text-align: right;">






<h2>دریافت یک ستون از یک شبکه</h2>
<p>برای دریافت یک ستون از یک شبکه، از <code>Z[:,اندیس ستون]</code> استفاده کنید.</p>
<p>برای دریافت دومین ستون از یک شبکه، از <code>Z[:,1]</code> استفاده کنید.</p>

</div>



In [54]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z[:,2])

[2 5 8]


<div dir="rtl" style="text-align: right;">





<h2>دریافت یک مینی‌شبکه از یک شبکه</h2>
<p>برای دریافت زیرمجموعه‌ای از یک شبکه، بنویسید: <code>Z[اندیس ردیف:,اندیس ستون:]</code>.</p>
<p>برای دریافت زیرمجموعه‌ای از شبکه شامل اولین ردیف به بعد تا انتها و اولین ستون به بعد تا انتها، بنویسید: <code>Z[1:,1:]</code>.</p>





</div>

In [55]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z[1:,1:])

[[4 5]
 [7 8]]


<div dir="rtl" style="text-align: right;">



<h2>چینش مقادیر از یک شبکه در یک مینی‌شبکه</h2>
<p>برای دریافت مقادیر از گوشه‌های یک شبکه و چیدمان آن‌ها در فرمت شبکه، بنویسید: <code>Z[::row_size-1, ::column_size-1]</code></p>
<p>برای دریافت مقادیر در اندیس‌ها (0,0)، (0,2)، (2,0)، (2,2) و چیدمان آن‌ها در فرمت شبکه، بنویسید: <code>Z[::2, ::2]</code></p>





</div>

In [56]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z[::2,::2])

[[0 2]
 [6 8]]


<div dir="rtl" style="text-align: right;">





<h2>دریافت اندیس‌های خاص از یک شبکه</h2>
<p>برای دریافت مقادیر اندیس‌های خاص مانند (0,0) و (1,2) بنویسید: <code>Z[[0,1],[0,2]]</code>.</p>





</div>

In [57]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z[[0,1],[0,2]])

[0 5]


<div dir="rtl" style="text-align: right;">



<ul>
<li>در <code>Z[[0,1],[0,2]]</code>، لیست اول [0,1] اندیس‌های ردیف را نشان می‌دهد در حالی که لیست دوم [0,2] اندیس‌های ستون را نشان می‌دهد.</li>
<li>مقدار 0 در ردیف 0 و ستون 0 از آرایه NumPy Z قرار دارد، که به عنوان اولین مقادیر از هر دو لیست نشان داده شده‌است.</li>
<li>مقدار 5 در ردیف 1 و ستون 2 از آرایه NumPy Z قرار دارد، که به عنوان دومین مقدار از هر دو لیست نشان داده شده‌است.</li>
</ul>

</div>

<div dir="rtl" style="text-align: right;">
<h1>پخش (Broadcasting) در NumPy</h1>


<h2>پخش در NumPy چیست؟</h2>
<p>اصطلاح پخش توصیف می‌کند که چگونه numpy با آرایه‌هایی با اشکال مختلف در طی عملیات حسابی رفتار می‌کند. با توجه به برخی محدودیت‌ها، آرایه کوچک‌تر در سراسر آرایه بزرگ‌تر "پخش" می‌شود تا اشکال سازگاری داشته باشند. پخش یک وسیله برای برداری کردن عملیات‌های آرایه فراهم می‌کند.</p>

<h2>قوانین کلی برای پخش</h2>
<p>هنگام کار با دو آرایه، NumPy اشکال آن‌ها را به صورت عنصر به عنصر مقایسه می‌کند. این مقایسه از ابعاد آخر شروع می‌شود و به سمت جلو پیش می‌رود. دو بعد با اندازه N با هم سازگار هستند زمانی که:</p>

<ul>
<li>آن‌ها برابر هستند، یا</li>
<li>یکی از آن‌ها مقدار منفرد است</li>
<li>یکی N*N و دیگری N*1 است</li>
<li>یکی N*N و دیگری 1*N است</li>
</ul>

<h2>مثال‌ها</h2>
<p>مفهوم پخش از طریق کد در مثال‌های زیر توضیح داده شده‌است:</p>

<h3>زمانی که یک عملوند N*N و دیگری 1*1 است</h3>




</div>


In [58]:
import numpy as np
Z1 = np.arange(9).reshape(3,3)
Z2 = 1
print(Z1 + Z2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<div dir="rtl" style="text-align: right;">


<h3>زمانی که یک عملوند N*N و دیگری N*1 است</h3>


</div>


In [59]:
import numpy as np
Z1 = np.arange(9).reshape(3,3)
Z2 = np.arange(3)[::-1].reshape(3,1)
print(Z1 + Z2)
   

[[2 3 4]
 [4 5 6]
 [6 7 8]]


<div dir="rtl" style="text-align: right;">




<h3>زمانی که یک عملوند N*N و دیگری 1*N است</h3>

</div>


In [60]:
import numpy as np
Z1 = np.arange(9).reshape(3,3)
Z2 = np.arange(3)[::-1]
print(Z1 + Z2)

[[2 2 2]
 [5 5 5]
 [8 8 8]]


<div dir="rtl" style="text-align: right;">
<h1>بردارسازی در NumPy</h1>

<p>بردارسازی، به زبان ساده، به معنای بهینه‌سازی الگوریتم است به گونه‌ای که بتواند چندین عملیات را از یک دستور واحد اجرا کند. NumPy کاملاً در مورد بردارسازی است. اگر با پایتون آشنا هستید، این یکی از اصلی‌ترین سختی‌هایی است که با آن مواجه خواهید شد، زیرا باید روش فکر کردن خود را تغییر دهید و دوستان جدید شما  "بردارها"، "آرایه‌ها"، "نماها" یا "ufuncs" باشند.</p>
<p>توجه: یک دستور به نام 
<code>timeit</code>
 در تمام کدها استفاده می‌شود. این ابزار برای اندازه‌گیری زمان اجرای تکه‌های کوچک کد است. میتوانید کپی‌رایت آن را در بالای کد ببینید.</p>

<h2>رویکرد شیء‌گرا</h2>
<p>بیایید یک مثال بسیار ساده را در نظر بگیریم، یک پیاده‌روی تصادفی. یک رویکرد شیء‌گرا احتمالی می‌تواند شامل تعریف کلاس RandomWalker و نوشتن یک متد walk باشد که موقعیت فعلی را پس از هر قدم (تصادفی) بازمی‌گرداند. این روش خوب و خوانا است، اما کند است:</p>
</div>


In [61]:
# کد زیر تنها با تغییرات بسیار جزئی منبع اصلی آمده آورده شده است

# -----------------------------------------------------------------------------
# From Numpy to Python
# Copyright (2017) Nicolas P. Rougier - BSD license
# More information at https://github.com/rougier/numpy-book
# -----------------------------------------------------------------------------
def sysinfo():
    import sys
    import time
    import numpy as np
    import scipy as sp
    import matplotlib

    print("Date:       %s" % (time.strftime("%D")))
    version = sys.version_info
    major, minor, micro = version.major, version.minor, version.micro
    print("Python:     %d.%d.%d" % (major, minor, micro))
    print("Numpy:     ", np.__version__)
    print("Scipy:     ", sp.__version__)
    print("Matplotlib:", matplotlib.__version__)

    

def timeit(stmt, globals):
    import timeit as _timeit
    import numpy as np
    
    # تقریب تقریبی یک اجرای واحد
    trial = _timeit.timeit(stmt, globals=globals, number=1)
    
    # حداکثر مدت زمان
    duration = 1.0
    
    # تعداد تکراره
    repeat = 3
    
    # محاسبه تعداد آزمایش‌های گرد شده
    number = max(1,int(10**np.floor(np.log(duration/trial/repeat)/np.log(10))))
    
    # تنها بهترین اجرا را گزارش می‌کند
    best = min(_timeit.repeat(stmt, globals=globals, number=number, repeat=repeat))

    units = {"usec": 1, "msec": 1e3, "sec": 1e6}
    precision = 3
    usec = best * 1e6 / number
    if usec < 1000:
        print("%d loops, best of %d: %.*g usec per loop" % (number, repeat,
                                                            precision, usec))
    else:
        msec = usec / 1000
        if msec < 1000:
            print("%d loops, best of %d: %.*g msec per loop" % (number, repeat,
                                                                precision, msec))
        else:
            sec = msec / 1000
            print("%d loops, best of %d: %.*g sec per loop" % (number, repeat,
                                                               precision, sec))
   # نمایش نتایج
    # print("%d loops, best of %d: %g sec per loop" % (number, repeat, best/number))

    
def info(Z):
    import numpy as np
        
    print("------------------------------")
    print("Interface (item)")
    print("  shape:      ", Z.shape)
    print("  dtype:      ", Z.dtype)
    print("  size:       ", Z.size)
    if np.isfortran(Z):
        print("  order:       ☐ C  ☑ Fortran")
    else:
        print("  order:       ☑ C  ☐ Fortran")
    print("")
    print("Memory (byte)")
    print("  item size:  ", Z.itemsize)
    print("  array size: ", Z.size*Z.itemsize)
    print("  strides:    ", Z.strides)
    print("")
    print("Properties")
    if Z.flags["OWNDATA"]:
        print("  own data:    ☑ Yes  ☐ No")
    else:
        print("  own data:    ☐ Yes  ☑ No")
    if Z.flags["WRITEABLE"]:
        print("  writeable:   ☑ Yes  ☐ No")
    else:
        print("  writeable:   ☐ Yes  ☑ No")
    if np.isfortran(Z) and Z.flags["F_CONTIGUOUS"]:
        print("  contiguous:  ☑ Yes  ☐ No")
    elif not np.isfortran(Z) and Z.flags["C_CONTIGUOUS"]:
        print("  contiguous:  ☑ Yes  ☐ No")
    else:
        print("  contiguous:  ☐ Yes  ☑ No")
    if Z.flags["ALIGNED"]:
        print("  aligned:     ☑ Yes  ☐ No")
    else:
        print("  aligned:     ☐ Yes  ☑ No")
    print("------------------------------")
    print()
    


In [62]:


import random
class RandomWalker:
  def __init__(self):
           self.position = 0
  def walk(self, n): # راه‌رفتن
    self.position = 0
    for i in range(n):
      yield self.position 
      self.position += 2*random.randint(0, 1) - 1
      # پس از هر گام تصادفی، موقعیت فعلی را برمی‌گرداند
           
walker = RandomWalker() # ایجاد نمونه‌ای از کلاس راه رفتن
walk = [position for position in walker.walk(1000)]# فراخوانی تابع راه رفتن

walker = RandomWalker()
timeit("[position for position in walker.walk(n=10000)]", globals())
# محاسبه تعداد حلقه‌های کلی و زمان هر حلقه


10 loops, best of 3: 8.91 msec per loop


<div dir="rtl" style="text-align: right;">

<p>در اینجا، حلقه‌ها تعداد کل چرخه‌های CPU مورد نیاز در طول یک پیاده‌روی تصادفی هستند و زمان بیان شده به میلی‌ثانیه، زمان لازم برای هر چرخه را نشان می‌دهد.</p>

<h2>رویکرد حلقه(شمارنده)</h2>
<p>برای چنین مشکل ساده‌ای، ما احتمالاً می‌توانیم تعریف کلاس را حذف کرده و فقط روی متد walk تمرکز کنیم که موقعیت‌های متوالی را پس از هر قدم تصادفی محاسبه می‌کند. این متد جدید برخی چرخه‌های CPU را ذخیره می‌کند اما نه زیاد، زیرا این تابع تقریباً همانند رویکرد شیء‌گرا است و چند چرخه‌ای که ذخیره شده‌اند احتمالاً از مکانیزم‌های داخلی شیء‌گرای پایتون می‌آیند.</p>
</div>


In [63]:

import random
def random_walk(n):
    position = 0
    walk = [position]
    for i in range(n):
        position += 2*random.randint(0, 1)-1 # موقعیت مقادیر تصادفی را به خود اختصاص می‌دهد
        walk.append(position)# موقعیت را به پیاده‌روی اضافه می‌کند
    return walk

walk = random_walk(1000) # فراخوانی تابع پیاده‌روی تصادفی
timeit("random_walk(n=10000)", globals()) # محاسبه تعداد حلقه‌های کلی و زمان هر حلقه

10 loops, best of 3: 8.56 msec per loop


<div dir="rtl" style="text-align: right;">
<h2>رویکرد برداری</h2>
<p>برای رویکرد برداری، می‌توانیم از Itertools یا NumPy استفاده کنیم.</p>

<h3>1. Itertools</h3>
<p>Itertools یک ماژول پایتون است که مجموعه‌ای از توابع برای ایجاد تکرارکننده‌ها برای حلقه‌زنی کارآمد ارائه می‌دهد. اگر متوجه شویم که یک پیاده‌روی تصادفی تجمعی از قدم‌ها است، می‌توانیم تابع را با اول تولید کردن تمام قدم‌ها و سپس تجمع آن‌ها بدون هیچ حلقه‌ای بازنویسی کنیم.</p>

</div>


In [64]:

from itertools import accumulate 
import random 
def random_walk_faster(n=1000):
  steps = random.choices([-1,+1], k=n)
  return [0]+list(accumulate(steps))# دریافت تعداد کلی گام‌ها 

walk = random_walk_faster(1000) 
timeit("random_walk_faster(n=10000)", globals()) # محاسبه تعداد حلقه‌های کلی و زمان هر حلقه

100 loops, best of 3: 1.82 msec per loop


<div dir="rtl" style="text-align: right;">
<p>در واقع، ما تابع خود را برداری کرده‌ایم. به جای اینکه در حلقه برای انتخاب قدم‌های متوالی و افزودن آن‌ها به موقعیت فعلی بمانیم، ابتدا تمام قدم‌ها را یکجا تولید کردیم و از تابع <code>accumulate</code> برای محاسبه تمام موقعیت‌ها استفاده کردیم. ما حلقه را حذف کردیم و این امر باعث شده است که کارها سریع‌تر انجام شوند.</p>


<h3>2. NumPy</h3>

<p>ما ۸۵٪ زمان محاسبه را نسبت به نسخه قبلی بهتر کردیم، که قدم خوبی است. اما مزیت این نسخه جدید این است که بردارسازی NumPy را بسیار ساده‌تر است. ما فقط باید فراخوانی‌های itertools را به فراخوانی‌های NumPy تبدیل کنیم:</p>


</div>



In [65]:

import numpy as np
def random_walk_fastest(n=1000):
    #s' در انتخاب NumPy وجود ندارد (Python choice & choices را ارائه می‌دهد))
    steps = np.random.choice([-1,+1], n)
    return np.cumsum(steps) #بازگرداندن جمع تجمعی گام‌ها در یک محور مشخص

walk = random_walk_fastest(1000)
timeit("random_walk_fastest(n=1000)", globals())
# محاسبه تعداد حلقه‌های کلی و زمان هر حلقه

100 loops, best of 3: 52.3 usec per loop


<div dir="rtl" style="text-align: right;">
<h1>خوانایی در مقابل سرعت</h1>




<p>NumPy یک کتابخانه بسیار قدرتمند است و شما می‌توانید با آن شگفتی‌ها خلق کنید، اما اغلب اوقات، این موضوع به قیمت خوانایی کد تمام می‌شود. اگر کد خود را هنگام نوشتن توضیح ندهید، پس از چند هفته (یا احتمالاً چند روز) نخواهید توانست تشخیص دهید که یک تابع چه کاری انجام می‌دهد.</p>

<p>برای مثال، آیا می‌توانید بگویید دو تابع زیر چه کاری انجام می‌دهند؟ احتمالاً می‌توانید برای اولی تشخیص دهید، اما برای دومی بعید است.</p>


</div>


In [66]:
import numpy as np
# خوانایی بیشتر اما سرعت کمتر
def function_1(seq, sub): 
    return [i for i in range(len(seq) - len(sub) +1) if seq[i:i+len(sub)] == sub]

# سرعت بیشتر و خوانایی کمتر
def function_2(seq, sub):
    target = np.dot(sub, sub)
    candidates = np.where(np.correlate(seq, sub, mode='valid') == target)[0]
    check = candidates[:, np.newaxis] + np.arange(len(sub))
    mask = np.all((np.take(seq, check) == sub), axis=-1)
    return candidates[mask]

seq=[12, 10, 2, 45, 13, 65, 11, 8, 5]
sub=[11, 8]
print("Function 1:",function_1(seq,sub))
print("Function 2:",function_2(seq,sub))

Function 1: [6]
Function 2: [6]


<div dir="rtl" style="text-align: right;">





<p>در این کد، هر دو تابع شاخص زیردنباله‌ای در دنباله را باز می‌گردانند. دنباله [12, 10, 2, 45, 13, 65, 11, 8, 5] است و زیردنباله [11, 8] است. شاخص زیردنباله در دنباله 6 است. همانطور که حدس زده‌اید، تابع دوم نسخه بهینه‌سازی شده برداری، بهینه‌سازی شده و سریع‌تر NumPy از تابع اول است. این تابع ۱۰ برابر سریع‌تر از نسخه خالص پایتون است، اما خوانایی آن بسیار دشوار است.</p>
</div>
