<div dir="rtl" style="text-align: right;">
<h1>نماها 
views
 و کپی‌ها
 copies</h1>


<p>نماها و کپی‌ها مفاهیم مهمی برای بهینه‌سازی محاسبات عددی شما هستند. حتی اگر ما قبلاً آن‌ها را در بخش قبلی دستکاری کرده‌ایم، داستان کامل کمی پیچیده‌تر است.</p>

<h2>دسترسی مستقیم و غیرمستقیم</h2>

<p>هنگام اجرای یک دستور numpy، یا یک کپی از آرایه ورودی ایجاد می‌شود یا یک نما ارائه می‌دهد. وقتی محتویات فیزیکی در مکان دیگری ذخیره شده‌اند، آن را کپی می‌نامیم. اگر از سوی دیگر، نمای متفاوتی از همان محتوای حافظه ارائه شود، آن را نما می‌نامیم.</p>

<h3>فهرست‌بندی و فهرست‌بندی پیچیده</h3>

<p>ابتدا باید بین فهرست‌بندی و فهرست‌بندی پیچیده تمایز قائل شویم. اولی همیشه یک نما برمی‌گرداند در حالی که دومی یک کپی برمی‌گرداند. این تفاوت مهم است زیرا در مورد اول، تغییر نما باعث تغییر آرایه پایه می‌شود در حالی که این در مورد دوم صدق نمی‌کند:</p>
</div>


In [4]:
import numpy as np

Z = np.zeros(9)
Z_view = Z[:3] 
Z_view[...] = 1 # Z_view آرایه پایه 'Z' را تغییر می‌دهد
print(Z)
Z = np.zeros(9)
Z_copy = Z[[0,1,2]]
Z_copy[...] = 1 # Z_copy آرایه پایه 'Z' را تغییر نمی‌دهد
print(Z)

[1. 1. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


<div dir="rtl" style="text-align: right;">
<p>بنابراین، اگر به فهرست‌بندی پیچیده نیاز دارید، بهتر است کپی از آرایه خود نگه دارید.</p>


</div>


In [5]:
import numpy as np
Z = np.zeros(9) 
index = [0,1,2]
Z[index] = 1 # در اندیس‌های 0, 1, و 2 عدد 1 را ذخیره کن
print(Z)

[1. 1. 1. 0. 0. 0. 0. 0. 0.]


<div dir="rtl" style="text-align: right;">


<p>اگر مطمئن نیستید که نتیجه فهرست‌بندی شما نما است یا کپی، می‌توانید پایه نتیجه خود را بررسی کنید. اگر پایه آن None باشد، پس نتیجه شما یک کپی است:</p>



</div>

In [6]:
import numpy as np
Z = np.random.uniform(0,1,(5,5)) # نمونه‌ای از توزیع یکنواخت
Z1 = Z[:3,:]
#print("Z1",Z1)
Z2 = Z[[0,1,2], :]
#print("Z2",Z2)
print(np.allclose(Z1,Z2)) # در صورتی که دو آرایه با محدوده‌ای به صورت المانی به هم نزدیک باشند True را برمی‌گرداند
print(Z1.base is Z)# اگر حافظه z1 با z اشتراک داشته باشد true بر می‌گرداند
print(Z2.base is Z)
print(Z2.base is None) # اگر z2 حافظه اشتراکی نداشته باشد true  را برمی‌گرداند

True
True
False
True


<div dir="rtl" style="text-align: right;">




<p>در کد بالا می‌توانیم ببینیم که Z1.base is Z مقدار 
True 
را برمی‌گرداند. زیرا 
Z1
 حافظه 
 Z
  را به اشتراک می‌گذارد و 
  Z1
   یک کپی از 
   Z ایجاد می‌کند. 
   Z2.base is Z
    مقدار False  را برمی‌گرداند زیرا Z2 یک نما از Z را فراهم می‌کند، بنابراین حافظه Z را به اشتراک نمی‌گذارد.</p>
</div>

<div dir="rtl" style="text-align: right;">
<h2>Ravel و Flatten</h2>
<p>برخی از توابع 
NumPy
 هنگامی که ممکن است یک نما برمی‌گردانند، مانند <code>ravel</code>، در حالی که برخی دیگر همیشه یک کپی برمی‌گردانند، مانند <code>flatten</code>. مثال زیر مفهوم <code>ravel</code> و <code>flatten</code> را از طریق کد توضیح می‌دهد:</p>




</div>


In [7]:
import numpy as np

Z = np.zeros((5,5))
print("Z:\n",Z)
print("Z.ravel().base:\n",Z.ravel().base)
print("Z.ravel().base is Z:",Z.ravel().base is Z) # اگر حافظه‌ی Z.ravel() با Z مشترک باشد، True برمی‌گرداند

print("\nZ[::2,::2].ravel():\n",Z[::2,::2].ravel())
print("\nZ[::2,::2].ravel().base is Z:",Z[::2,::2].ravel().base is Z)# اگر حافظه‌ی Z[::2,::2].ravel() با Z مشترک باشد، True برمی‌گرداند

print("\nZ.flatten()\n:",Z.flatten())
print("Z.flatten.base is Z:",Z.flatten().base is Z)# اگر حافظه‌ی Z.flatten() با Z مشترک باشد، True برمی‌گرداند




Z:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Z.ravel().base:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Z.ravel().base is Z: True

Z[::2,::2].ravel():
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]

Z[::2,::2].ravel().base is Z: False

Z.flatten()
: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
Z.flatten.base is Z: False


<div dir="rtl" style="text-align: right;">
<h2>کپی موقت</h2>
<p>کپی‌ها می‌توانند به صورت صریح مانند بخش قبلی ایجاد شوند، اما معمول‌ترین حالت، ایجاد نسخه‌های میانی به صورت ضمنی است. این زمانی اتفاق می‌افتد که شما محاسباتی را با آرایه‌ها انجام می‌دهید:</p>

</div>


In [8]:
import numpy as np

X = np.ones(10, dtype=int)  # ایجاد یک آرایه X از اندازه ۱۰ حاوی یک‌ها
Y = np.ones(10, dtype=int)  # ایجاد یک آرایه Y از اندازه ۱۰ حاوی یک‌ها
A = 2*X + 2*Y  # ذخیره ۲*X + ۲*Y در A
print("X:", X)
print("Y:", Y)
print("A=2*X + 2*Y :\nA:", A)

X: [1 1 1 1 1 1 1 1 1 1]
Y: [1 1 1 1 1 1 1 1 1 1]
A=2*X + 2*Y :
A: [4 4 4 4 4 4 4 4 4 4]


<div dir="rtl" style="text-align: right;">



<p>در مثال بالا، سه آرایه میانی ایجاد شده‌اند. یکی برای نگه داشتن نتیجه ۲*X، یکی برای نگه داشتن نتیجه ۲*Y و آخری برای نگه داشتن نتیجه ۲*X+۲*Y. در این مورد خاص، آرایه‌ها به اندازه کافی کوچک هستند و این واقعا تفاوتی ایجاد نمی‌کند. با این حال، اگر آرایه‌های شما بزرگ هستند، باید در مورد چنین عباراتی دقت کنید و بیندیشید که آیا می‌توانید آن را به شکل دیگری انجام دهید. به عنوان مثال، اگر فقط نتیجه نهایی مهم است و شما بعدا به X یا Y نیاز ندارید، راه‌حل جایگزین می‌تواند به صورت زیر باشد:</p>
</div>


In [9]:
import numpy as np
X = np.ones(10, dtype=int) # ایجاد یک آرایه X با اندازه 10 که شامل یک‌ها است
Y = np.ones(10, dtype=int) # ایجاد یک آرایه Y با اندازه 10 که شامل یک‌ها است
print("X:",X,"Y:",Y,"\n np.multiply(X, 2, out=X)")
np.multiply(X, 2, out=X) # X را در 2 ضرب کن و نتیجه را در X ذخیره کن
print("X:",X,"Y:",Y,"\n np.multiply(Y, 2, out=Y)")
np.multiply(Y, 2, out=Y)# Y را در 2 ضرب کن و نتیجه را در Y ذخیره کن
print("X:",X,"Y:",Y,"\n np.add(X, Y, out=X)")
np.add(X, Y, out=X)# X و Y را با هم جمع کن و نتیجه را در X ذخیره کن
print("X:",X,"Y:",Y)

X: [1 1 1 1 1 1 1 1 1 1] Y: [1 1 1 1 1 1 1 1 1 1] 
 np.multiply(X, 2, out=X)
X: [2 2 2 2 2 2 2 2 2 2] Y: [1 1 1 1 1 1 1 1 1 1] 
 np.multiply(Y, 2, out=Y)
X: [2 2 2 2 2 2 2 2 2 2] Y: [2 2 2 2 2 2 2 2 2 2] 
 np.add(X, Y, out=X)
X: [4 4 4 4 4 4 4 4 4 4] Y: [2 2 2 2 2 2 2 2 2 2]


<div dir="rtl" style="text-align: right;">
<p>با استفاده از این راه‌حل جایگزین، هیچ آرایه موقتی ایجاد نشده است. مشکل این است که موارد زیاد دیگری وجود دارد که در آن‌ها نیاز به ایجاد چنین کپی‌هایی است و این بر عملکرد تأثیر می‌گذارد، همانطور که در مثال زیر نشان داده شده است:</p>

</div>


In [10]:
import numpy as np
from utils.tools import timeit

def test(X,Y):
  timeit("Z=X + 2.0*Y", globals()) # 	زمان گرفته شده برای Z=X + 2.0*Y
  timeit("Z = X + 2*Y", globals()) # زمان گرفته شده برای Z=X + 2*Y
  timeit("np.add(X, Y, out=X); np.add(X, Y, out=X)", globals())
  # زمان گرفته شده برای np.add(X, Y, out=X); np.add(X, Y, out=X)
   
X = np.ones(100000000, dtype=int) 
Y = np.ones(100000000, dtype=int)
test(X,Y)

1 loops, best of 3: 546 msec per loop
1 loops, best of 3: 405 msec per loop
1 loops, best of 3: 296 msec per loop


<div dir="rtl" style="text-align: right;">


<p>در این مثال، به دلیل حجم بالای داده‌ها و پیچیدگی عملیات، ایجاد نسخه‌های موقت اجتناب‌ناپذیر است و ممکن است بر عملکرد سیستم تأثیر بگذارد. راه‌حل‌های بهینه‌سازی ممکن است شامل بازنویسی عملیات به شکلی باشد که کمترین کپی ممکن را ایجاد کند.</p>
</div>